## Archived tweets for \_MilkNCookiez\_
### Content warning: racism and antisemitism
More information: https://github.com/TwitterArchives/KYE#readme

The list below includes 106 archived tweets by
[\_MilkNCookiez\_](https://twitter.com/_MilkNCookiez_).




This report was generated by [@AcctHunter](https://twitter.com/accthunter) using ✨[cancel-culture](https://github.com/travisbrown/cancel-culture)✨,
an open source project by [Travis Brown](https://twitter.com/travisbrown). You can create your own
updated version of this document by checking out and configuring the repository and then running
the following commands:

```bash
$ cargo build --release
$ target/release/twcc deleted-tweets --report _MilkNCookiez_
```

Please note that all tweets quoted here are sourced from the
[Wayback Machine](https://web.archive.org) and were not directly accessed through the Twitter API or
any Twitter client.



* [16 October 2020](https://web.archive.org/web/20201016231836/https://twitter.com/_MilkNCookiez_/status/1317243536547344384): Where's Shane?
* [16 October 2020](https://web.archive.org/web/20201016230057/https://twitter.com/_MilkNCookiez_/status/1317239062353244160): Well, well, well... pic.twitter.com/RU5DtBccMF
* [16 October 2020](https://web.archive.org/web/20201016225138/https://twitter.com/_MilkNCookiez_/status/1317236706450362370): He was probably smoking crack with Hunter Biden.
* [16 October 2020](https://web.archive.org/web/20201016224850/https://twitter.com/_MilkNCookiez_/status/1317235977039998976): Lol. 😁😉
* [16 October 2020](https://web.archive.org/web/20201016224723/https://twitter.com/_MilkNCookiez_/status/1317235705249112065): Probably tweeting from solitary confinement. Has nothing better to do.
* [16 October 2020](https://web.archive.org/web/20201016224537/https://twitter.com/_MilkNCookiez_/status/1317235195641098240): 😈  Caffeine weenie!
* [16 October 2020](https://web.archive.org/web/20201016224140/https://twitter.com/_MilkNCookiez_/status/1317234231198638080): That one and the Miami Cola are the only ones I like, unless it's coffee flavored. 300 mg of caffeine. A lot more than a monster. 😁
* [16 October 2020](https://web.archive.org/web/20201016224031/https://twitter.com/_MilkNCookiez_/status/1317233896900079616): I don't think a shower would help.
* [16 October 2020](https://web.archive.org/web/20201016223959/https://twitter.com/_MilkNCookiez_/status/1317233815450910721): Lol
* [16 October 2020](https://web.archive.org/web/20201016223943/https://twitter.com/_MilkNCookiez_/status/1317233665378643969): Dey wuz hygienes n sheit.
* [16 October 2020](https://web.archive.org/web/20201016223741/https://twitter.com/_MilkNCookiez_/status/1317233173021958144): You'll probably feel like you need a shower after having read my tweets.  https://twitter.com/BobStoneArtist/status/1317231772191653894  pic.twitter.com/FIyRvOSTv9
* [16 October 2020](https://web.archive.org/web/20201016223423/https://twitter.com/_MilkNCookiez_/status/1317232368869015552): This nigger loves his massa https://twitter.com/BobStoneArtist/status/1317231975594340355
* [16 October 2020](https://web.archive.org/web/20201016223246/https://twitter.com/_MilkNCookiez_/status/1317231951967784960): This nigger loves his massa. https://twitter.com/BobStoneArtist/status/1317231483652919299
* [16 October 2020](https://web.archive.org/web/20201016223134/https://twitter.com/_MilkNCookiez_/status/1317231663441534977): NIGGER NIGGER NIGGER NIGGER NIGGER NIGGER  I can do this all day. https://twitter.com/BobStoneArtist/status/1317231483652919299
* [16 October 2020](https://web.archive.org/web/20201016223038/https://twitter.com/_MilkNCookiez_/status/1317231454011629568): Because they lack discernment. Not only that, but they can't live without their jews. No matter how many times they claim to hate them, "jews are the enemy", they still run right back to that enemy for guidance.
* [16 October 2020](https://web.archive.org/web/20201016222648/https://twitter.com/_MilkNCookiez_/status/1317230476784889856): N I G G E R https://twitter.com/BobStoneArtist/status/1317230383042338816
* [16 October 2020](https://web.archive.org/web/20201016222420/https://twitter.com/_MilkNCookiez_/status/1317229892631605248): No. That's just typical black theft.
* [16 October 2020](https://web.archive.org/web/20201016222344/https://twitter.com/_MilkNCookiez_/status/1317229706136014849): Lol. What a cry baby
* [16 October 2020](https://web.archive.org/web/20201016230606/https://twitter.com/_MilkNCookiez_/status/1317225128183304193): That's more like "taking away", which is what they're good at.
* [16 October 2020](https://web.archive.org/web/20201016220154/https://twitter.com/_MilkNCookiez_/status/1317224230853906433): I  HAD   TO  😆
* [16 October 2020](https://web.archive.org/web/20201016220311/https://twitter.com/_MilkNCookiez_/status/1317224140965752832): Maybe people don't know about 'black contributions' because there literally aren't any. Mud cookies and cow-piss spas don't count. Sorry. https://twitter.com/BobStoneArtist/status/1317212624111718401
* [16 October 2020](https://web.archive.org/web/20201016215715/https://twitter.com/_MilkNCookiez_/status/1317223048164954112): You're such a fag. https://twitter.com/Know_More_News/status/1317126114762878976
* [16 October 2020](https://web.archive.org/web/20201016215201/https://twitter.com/_MilkNCookiez_/status/1317221659024052225): You can't, obviously. Cleopatra was of the Ptolemy dynasty, a family of pure Greek stock. Guess what that means? She was 100% European. Lol. Dumb nigger. https://twitter.com/noireshanghai/status/1317028438298005505
* [16 October 2020](https://web.archive.org/web/20201016214634/https://twitter.com/_MilkNCookiez_/status/1317220326082703360): MEAT AND POTATOES!! 🤗
* [16 October 2020](https://web.archive.org/web/20201016214322/https://twitter.com/_MilkNCookiez_/status/1317219498395537408): No. Too many jewish infiltrators.
* [16 October 2020](https://web.archive.org/web/20201016214035/https://twitter.com/_MilkNCookiez_/status/1317218852581773313): 🤗🤪 pic.twitter.com/GUoixEtVPn
* [16 October 2020](https://web.archive.org/web/20201016213606/https://twitter.com/_MilkNCookiez_/status/1317217675253321738): Wish I had looked at the whole picture before quoting it. 🤣
* [16 October 2020](https://web.archive.org/web/20201016213501/https://twitter.com/_MilkNCookiez_/status/1317217461196894209): Lol
* [16 October 2020](https://web.archive.org/web/20201016213437/https://twitter.com/_MilkNCookiez_/status/1317217381920378880): Google your first name + apocalypse outfit and post the 1st image you get.   I swear, this the 1st image.  https://twitter.com/DuctTapeMan3/status/1317214770811047937  pic.twitter.com/2Ihhh9w4Cs
* [16 October 2020](https://web.archive.org/web/20201016204044/https://twitter.com/_MilkNCookiez_/status/1317203760096047105): YEEEES!!
* [16 October 2020](https://web.archive.org/web/20201016203618/https://twitter.com/_MilkNCookiez_/status/1317202659422597120): This platform is gaaaay
* [16 October 2020](https://web.archive.org/web/20201016203523/https://twitter.com/_MilkNCookiez_/status/1317202438886076416): Without downloading any new pictures, where are you at mentally?  https://twitter.com/nephilimcheeks/status/1317201121652322304  pic.twitter.com/TBIYr6vohc
* [16 October 2020](https://web.archive.org/web/20201016202747/https://twitter.com/_MilkNCookiez_/status/1317200535892545536): Lol.
* [16 October 2020](https://web.archive.org/web/20201016202415/https://twitter.com/_MilkNCookiez_/status/1317199646121365505): underwear - jew   Probably some kind of inside fecal joke.
* [16 October 2020](https://web.archive.org/web/20201016202200/https://twitter.com/_MilkNCookiez_/status/1317199039201382400): You have NO idea! pic.twitter.com/hEhoTrFMoX
* [16 October 2020](https://web.archive.org/web/20201016202605/https://twitter.com/_MilkNCookiez_/status/1317198654852141057): People are getting fed up with this (((bullshit))). Tik tock, small-hats! https://twitter.com/tafkag/status/1317046143939940353
* [16 October 2020](https://web.archive.org/web/20201016201016/https://twitter.com/_MilkNCookiez_/status/1317196127750344704): Nice!
* [16 October 2020](https://web.archive.org/web/20201016200400/https://twitter.com/_MilkNCookiez_/status/1317194364460830720): This doesn't sound Bolshevik at all. 😏 https://twitter.com/realDonaldTrump/status/1317063921375842305
* [16 October 2020](https://web.archive.org/web/20201016200150/https://twitter.com/_MilkNCookiez_/status/1317193970288525312): Move to Israel. It's where all of you (((based))) idiots belong. https://twitter.com/BasedHungary/status/1317117649692872706
* [16 October 2020](https://web.archive.org/web/20201016195637/https://twitter.com/_MilkNCookiez_/status/1317192701708677121): Hi, darlin! 🤗 Lovely music. Very relaxing.   How are you today?
* [16 October 2020](https://web.archive.org/web/20201016195458/https://twitter.com/_MilkNCookiez_/status/1317192237508292608): Haven't had anything weird happen as of late, but I've definitely had my share of paranormal (demonic) encounters. We've talked about them. Scary as hell.
* [16 October 2020](https://web.archive.org/web/20201016195339/https://twitter.com/_MilkNCookiez_/status/1317191849732239361): @GE_Campbellite  Wut up, Home Slice? 😁
* [16 October 2020](https://web.archive.org/web/20201016195143/https://twitter.com/_MilkNCookiez_/status/1317191474576908289): A very wise man.
* [16 October 2020](https://web.archive.org/web/20201016195115/https://twitter.com/_MilkNCookiez_/status/1317191298298736641): @RadioactiveRedn  I love you the most! You can't love me more, cuz there's no such thing as more than most. 😌😜😚💗
* [16 October 2020](https://web.archive.org/web/20201016194933/https://twitter.com/_MilkNCookiez_/status/1317190914025037824): GOOD AFTERNOON, BIGOTS! 💕  I just had to delete 14 more tweets. 🤗😏 pic.twitter.com/vkJ14eva1u
* [ 8 October 2020](https://web.archive.org/web/20201009114641/https://twitter.com/_MilkNCookiez_/status/1314122027171627009): Good to know that you're aware of the real (((problem))) and can at least recognize subversive bs when you see it.   Here's my archive page. Lots of good reading material for people like us...  https://archive.org/details/@knowyourenemy
* [ 8 October 2020](https://web.archive.org/web/20201009114641/https://twitter.com/_MilkNCookiez_/status/1314122027171627009): *cringe* 🤢
* [ 8 October 2020](https://web.archive.org/web/20201009113614/https://twitter.com/_MilkNCookiez_/status/1314120101709242370): You know where you are? You're in the jungle baby, and you're gonna diiiiiiie.... 🐒🌴  Seriously though. That sucks. I'm sorry you have to put up with that shit.
* [ 8 October 2020](https://web.archive.org/web/20201009113151/https://twitter.com/_MilkNCookiez_/status/1314118614098702336): We've been naturally repelled by them since we were born. They don't look like us, think like us, or act like us, and they sure as hell don't smell good like us. Even animals know better. Their less-than-animalistic behavior only exacerbates our natural instincts towards them.
* [ 8 October 2020](https://web.archive.org/web/20201009111953/https://twitter.com/_MilkNCookiez_/status/1314116995382603776): Thank you. I hate them too. We'll see what happens. 😊
* [ 8 October 2020](https://web.archive.org/web/20201009111240/https://twitter.com/_MilkNCookiez_/status/1314115410581581825): Racism is good. Racism is wise.
* [ 8 October 2020](https://web.archive.org/web/20201009121909/https://twitter.com/_MilkNCookiez_/status/1314115144515952642): But if I'm dead, you can't kill me. So there! pic.twitter.com/zVTrmuKqkd
* [ 8 October 2020](https://web.archive.org/web/20201008063758/https://twitter.com/_MilkNCookiez_/status/1314091910756139008): Making a mocha pie at midnight. Dough is in the fridge. Next step: mocha filling, then an espresso covered whipped topping. 🥧🤗
* [ 8 October 2020](https://web.archive.org/web/20201008044245/https://twitter.com/_MilkNCookiez_/status/1314063212237611009): One of my mercury fillings just fell out. Gonna call a dentist in the morning, provided I don't die of mercury poisoning in the meantime. If I don't come back, blame the jews. 😫
* [ 8 October 2020](https://web.archive.org/web/20201008040336/https://twitter.com/_MilkNCookiez_/status/1314052942324875266): Homemade pizza!   Yeah, bitches... that's pineapple! 😁😋 pic.twitter.com/q0s6kkyO6Y
* [ 8 October 2020](https://web.archive.org/web/20201008033851/https://twitter.com/_MilkNCookiez_/status/1314047580473487361): @redscarf76 Lol
* [ 8 October 2020](https://web.archive.org/web/20201008005210/https://twitter.com/_MilkNCookiez_/status/1314005633205628931): @mosthigh210 @Anon75559163 @Jerusalem_Post His mom was a Galilean, his brothers were Galileans, his disciples were Galileans, the 144,000 firstfruits redeemed unto God from among men (i.e. the FIRST Christians) were Israelites, not jews.  Galatians 3:16 &amp; 29. Romans 2:28 &amp; 29  There is no more physical Israel.
* [ 7 October 2020](https://web.archive.org/web/20201007232433/https://twitter.com/_MilkNCookiez_/status/1313982181597880320): 😁🤗 pic.twitter.com/SrtXDSvzon
* [ 7 October 2020](https://web.archive.org/web/20201007222937/https://twitter.com/_MilkNCookiez_/status/1313967854639669248): There's a simple solution.   We need less jews (and by less, I mean zero) in our country. https://twitter.com/ElijahSchaffer/status/1287228182916022272
* [ 7 October 2020](https://web.archive.org/web/20201007234628/https://twitter.com/_MilkNCookiez_/status/1313954561686605824): @RadioactiveRedn  ❤😘 pic.twitter.com/FC5YbRCTIS
* [ 7 October 2020](https://web.archive.org/web/20201007084813/https://twitter.com/_MilkNCookiez_/status/1313741965020721152): Welcome back, darlin. 🤗💕
* [ 7 October 2020](https://web.archive.org/web/20201007084813/https://twitter.com/_MilkNCookiez_/status/1313741965020721152): FOLLOW MY EVIL TWIN, NOW! 👇  https://twitter.com/Supra_Saint/status/1313741329290199040  pic.twitter.com/eEOYtKGcdK
* [ 7 October 2020](https://web.archive.org/web/20201007075409/https://twitter.com/_MilkNCookiez_/status/1313741096195813376): String the nigger up. https://twitter.com/Breaking911/status/1313630136982437890
* [ 7 October 2020](https://web.archive.org/web/20201007045842/https://twitter.com/_MilkNCookiez_/status/1313705287522549760): No! Neither should women.
* [ 7 October 2020](https://web.archive.org/web/20201007065334/https://twitter.com/_MilkNCookiez_/status/1313700457127108611): Native Americans are White.  https://twitter.com/tickleman20/status/1313608469044498432  pic.twitter.com/qLcYJQ9Paw
* [ 7 October 2020](https://web.archive.org/web/20201007042315/https://twitter.com/_MilkNCookiez_/status/1313687612788404224): This is a hideous kike. https://twitter.com/25th_Prestige/status/1313606082292453376
* [ 7 October 2020](https://web.archive.org/web/20201007045930/https://twitter.com/_MilkNCookiez_/status/1313678260430008322): Dinner: Pasta Carbonara with fresh peas and ham chunks added. 😋 pic.twitter.com/Yvb6AluJlT
* [ 6 October 2020](https://web.archive.org/web/20201007033649/https://twitter.com/_MilkNCookiez_/status/1313618665649041409): Germans gave us 'Nazis'.   jews created  #Antifa . https://twitter.com/ElijahSchaffer/status/1313523701418266626
* [ 6 October 2020](https://web.archive.org/web/20201007085115/https://twitter.com/_MilkNCookiez_/status/1313540341706887169): Hi, Jo! 🤗 How's your day going?
* [ 6 October 2020](https://web.archive.org/web/20201007015204/https://twitter.com/_MilkNCookiez_/status/1313564823892885504): @HateJunkie  Hiya, Joe. 🤗 How's everything going? I'm surprised you've managed to hold on to this account for so long. Lol. Mine seems to be hanging on for the moment. There's something strange goin on. 🤨 But hey.. I'm not complaining. 😉
* [ 6 October 2020](https://web.archive.org/web/20201007085115/https://twitter.com/_MilkNCookiez_/status/1313540341706887169): Hi, Alex. 🤗 Thank you. Hope you're having a good evening. 🌅
* [ 6 October 2020](https://web.archive.org/web/20201007085115/https://twitter.com/_MilkNCookiez_/status/1313540341706887169): Good morning, Engineer. Thank you. Same to you. 🤗
* [ 6 October 2020](https://web.archive.org/web/20201006185239/https://twitter.com/_MilkNCookiez_/status/1313541696064385026): @RadioactiveRedn  Hey, hot stuff. Need me to do anything for you today? I miss you. ❤😘
* [ 6 October 2020](https://web.archive.org/web/20201007085115/https://twitter.com/_MilkNCookiez_/status/1313540341706887169): GOOOOD MORNING, NIGGER-HATERS! 🤗❤ pic.twitter.com/PzQKxb47Ur
* [ 6 October 2020](https://web.archive.org/web/20201006070903/https://twitter.com/_MilkNCookiez_/status/1313375703300096000): @nocturne_bat Cinnamon is a year-round spice. It shouldn't even be allowed to compete. 😌
* [ 5 October 2020](https://web.archive.org/web/20201006104944/https://twitter.com/_MilkNCookiez_/status/1312906058713583617): I seem to have a knack for getting under their skin. Lol.
* [ 5 October 2020](https://web.archive.org/web/20201005173146/https://twitter.com/_MilkNCookiez_/status/1312941779658788864): Any time, honey. 😘
* [ 5 October 2020](https://web.archive.org/web/20201005173146/https://twitter.com/_MilkNCookiez_/status/1312941779658788864): Follow 👇👇👇  https://twitter.com/MMacdhomhnaill/status/1312926432750903302
* [ 5 October 2020](https://web.archive.org/web/20201006082701/https://twitter.com/_MilkNCookiez_/status/1312935994409119744): God, I love this man. 😍 https://twitter.com/RadioactiveRedn/status/1312935323987451904
* [ 5 October 2020](https://web.archive.org/web/20201006104944/https://twitter.com/_MilkNCookiez_/status/1312906058713583617): There's an angry kike in my mentions. Whatever shall I do? 😈 pic.twitter.com/1nNSxK6QZ5
* [ 4 October 2020](https://web.archive.org/web/20201005025610/https://twitter.com/_MilkNCookiez_/status/1312874506432573440): @RadioactiveRedn  You're lookin mighty sexy today, baby! I love you. ❤😘
* [ 4 October 2020](https://web.archive.org/web/20201005043856/https://twitter.com/_MilkNCookiez_/status/1312870901168259072): HAPPY SUNDAY, BEAUTIFUL WHITE PEOPLE! 🤗❤ pic.twitter.com/G3hNL8UsRf
* [ 4 October 2020](https://web.archive.org/web/20201004213517/https://twitter.com/_MilkNCookiez_/status/1312690241220694016): Lmao! Look at this kike. 👇  Racism is civilization's immune system. We are born racist, you absolute faggot.  https://twitter.com/ToxicTeutonic/status/1312688695775035393
* [ 4 October 2020](https://web.archive.org/web/20201007164559/https://twitter.com/_MilkNCookiez_/status/1312615168031879169): Ding ding ding
* [ 4 October 2020](https://web.archive.org/web/20201007164559/https://twitter.com/_MilkNCookiez_/status/1312615168031879169): Anyone wanna guess how many times a day I say this? https://twitter.com/ThatOldSheepDog/status/1312470657460924416
* [ 4 October 2020](https://web.archive.org/web/20201006030609/https://twitter.com/_MilkNCookiez_/status/1312593460147318785): I don't want to hear about how someone fell off the bandwagon, I want to hear about how they overcame temptation. This is awesome! https://twitter.com/SimpWithALimp/status/1312587229341126656
* [ 4 October 2020](https://web.archive.org/web/20201004193405/https://twitter.com/_MilkNCookiez_/status/1312550764087177216): Evidence of black history would fit in the same shoebox as that of the holocaust. https://twitter.com/amnesty/status/1312003148584808455
* [ 3 October 2020](https://web.archive.org/web/20201005172211/https://twitter.com/_MilkNCookiez_/status/1312489092953763840): Who hates niggers more?
* [ 3 October 2020](https://web.archive.org/web/20201005114205/https://twitter.com/_MilkNCookiez_/status/1312487246713380864): Niggers can't swim https://twitter.com/1776retweets171/status/1312487117256232960
* [ 3 October 2020](https://web.archive.org/web/20201005060114/https://twitter.com/_MilkNCookiez_/status/1312435418537762818): 😸🤗❤   Hello, my beautiful friend! I hope you're feeling well today! 😘
* [ 3 October 2020](https://web.archive.org/web/20201005060114/https://twitter.com/_MilkNCookiez_/status/1312435418537762818): MORNIN, FAM. HAPPY SATURDAY. 🤗❤ pic.twitter.com/AL4FDqcVjt
* [ 3 October 2020](https://web.archive.org/web/20201005043724/https://twitter.com/_MilkNCookiez_/status/1312316299687550980): Just watched "How To Train Your Dragon". Very cute. pic.twitter.com/HVRvBpLJ02
* [ 3 October 2020](https://web.archive.org/web/20201006220540/https://twitter.com/_MilkNCookiez_/status/1312231032087748608): 🤗
* [ 3 October 2020](https://web.archive.org/web/20201006220540/https://twitter.com/_MilkNCookiez_/status/1312231032087748608): Dinner: French toast, hashbrowns, eggs, and ghost pepper-habanero sausage (for  @RadioactiveRedn ). 🔥 pic.twitter.com/swhrBluzLk
* [ 2 October 2020](https://web.archive.org/web/20201006163900/https://twitter.com/_MilkNCookiez_/status/1312152798985809920): My man came home stressed yesterday. I gave him a 30-minute back, neck, and head massage to help relax him. Whatever I can do to make his day easier, I'll do. https://twitter.com/whitney_nations/status/1312149053069639682
* [ 2 October 2020](https://web.archive.org/web/20201005203045/https://twitter.com/_MilkNCookiez_/status/1312141715550035968): Haahaahaa. Niggers are sick of jews too. https://twitter.com/BNONews/status/1312048271733424130
* [ 2 October 2020](https://web.archive.org/web/20201007080008/https://twitter.com/_MilkNCookiez_/status/1312136434485088256): @RadioactiveRedn  Can't wait to see you. 😍 Wanna go for a walk tonight? I'll let you hold my hand. ☺😘❤
* [ 2 October 2020](https://web.archive.org/web/20201005232438/https://twitter.com/_MilkNCookiez_/status/1311853518949548038): Any time, darlin. 😊
* [ 2 October 2020](https://web.archive.org/web/20201005232438/https://twitter.com/_MilkNCookiez_/status/1311853518949548038): Refollow 👇👇👇 https://twitter.com/BlanchedRob/status/1311839085493841922
* [ 2 October 2020](https://web.archive.org/web/20201005105505/https://twitter.com/_MilkNCookiez_/status/1311823721192022017): Well, of course there's a jewish chapter. Who do you think runs the entire "proud boys" organization? FYI: They run them all. https://twitter.com/jdforward/status/1311759053400485889
* [ 1 October 2020](https://web.archive.org/web/20201005005837/https://twitter.com/_MilkNCookiez_/status/1311444643985326081): 😁❤
* [ 1 October 2020](https://web.archive.org/web/20201005053001/https://twitter.com/_MilkNCookiez_/status/1311501945991884801): You sure about that?  https://twitter.com/dogbot5/status/1311297553456132096  pic.twitter.com/BnUCcggGBj
* [30 September 2020](https://web.archive.org/web/20201005005837/https://twitter.com/_MilkNCookiez_/status/1311444643985326081): That's a solid 8 for me. Not too bad. 😈 https://twitter.com/larknap/status/1311103579235799042
* [29 September 2020](https://web.archive.org/web/20201004193641/https://twitter.com/_MilkNCookiez_/status/1310856727445741569): I'm so sorry you're not sleeping well. 😔 Are you feeling any better? I hate that I can't help you somehow. *sigh*
* [29 September 2020](https://web.archive.org/web/20201004193641/https://twitter.com/_MilkNCookiez_/status/1310856727445741569): Lovely! 🤗
* [28 September 2020](https://web.archive.org/web/20201006205742/https://twitter.com/_MilkNCookiez_/status/1310377798712717313): Jesus.   Still is. https://twitter.com/HipieZs/status/1310234784258494465
