## Archived tweets for BehindUrBadDays
### Content warning: racism and antisemitism
More information: https://github.com/TwitterArchives/KYE#readme

The list below includes 191 archived tweets by
[BehindUrBadDays](https://twitter.com/BehindUrBadDays).




This report was generated by [@AcctHunter](https://twitter.com/accthunter) using ✨[cancel-culture](https://github.com/travisbrown/cancel-culture)✨,
an open source project by [Travis Brown](https://twitter.com/travisbrown). You can create your own
updated version of this document by checking out and configuring the repository and then running
the following commands:

```bash
$ cargo build --release
$ target/release/twcc deleted-tweets --report BehindUrBadDays
```

Please note that all tweets quoted here are sourced from the
[Wayback Machine](https://web.archive.org) and were not directly accessed through the Twitter API or
any Twitter client.



* [21 February 2021](https://web.archive.org/web/20210221111825/https://twitter.com/BehindUrBadDays/status/1363447826357891072): LOL. Well, I was a little more trusting, but I knew you were a good man. 😘
* [21 February 2021](https://web.archive.org/web/20210221111544/https://twitter.com/BehindUrBadDays/status/1363447238320680960): Go into it with confidence, but expect to be shut down occasionally. It happens. Don't let it keep you from trying again. You'll find the right one, at just the right time. :)
* [21 February 2021](https://web.archive.org/web/20210221111258/https://twitter.com/BehindUrBadDays/status/1363446489264119808): Umm.. you're screaming into one right now. 😌  😆
* [21 February 2021](https://web.archive.org/web/20210221111017/https://twitter.com/BehindUrBadDays/status/1363445798890049536): Don't ever give up.
* [21 February 2021](https://web.archive.org/web/20210221110844/https://twitter.com/BehindUrBadDays/status/1363445333242613760): It's  @RadioactiveRedn    Do you know him? That's my man. 😁 pic.twitter.com/nEjuzU7ENH
* [21 February 2021](https://web.archive.org/web/20210221110126/https://twitter.com/BehindUrBadDays/status/1363443664542986241): I moved. We were very far apart, but we spent months getting to know each other on the phone, etc. Talked every night, for hours. He's the love of my life.
* [21 February 2021](https://web.archive.org/web/20210221105336/https://twitter.com/BehindUrBadDays/status/1363441659896336387): I found mine here, almost exactly a year ago. We had been mutuals for about two years. He slid into my DMs after seeing a picture of me. I've never been happier. 😊  My advice: Observe him/her for a while before making a move, and be careful who you give personal information to. https://twitter.com/ElfReich4/status/1363400744661962752
* [21 February 2021](https://web.archive.org/web/20210221102806/https://twitter.com/BehindUrBadDays/status/1363435267902869507): It was good. 😁
* [21 February 2021](https://web.archive.org/web/20210221102642/https://twitter.com/BehindUrBadDays/status/1363434904059584514): 😘
* [21 February 2021](https://web.archive.org/web/20210221084809/https://twitter.com/BehindUrBadDays/status/1363410088535425024): It's easy to manipulate people when JEWS own all the media outlets.
* [21 February 2021](https://web.archive.org/web/20210221084549/https://twitter.com/BehindUrBadDays/status/1363409539975028738): If you left me a reply and I didn't answer, it's because I didn't get a notification. I'm not ignoring anyone, I promise. 🙃
* [21 February 2021](https://web.archive.org/web/20210221084014/https://twitter.com/BehindUrBadDays/status/1363408060346171393): Lol
* [21 February 2021](https://web.archive.org/web/20210221083419/https://twitter.com/BehindUrBadDays/status/1363406628360486912): pic.twitter.com/2tHVuVjMac
* [21 February 2021](https://web.archive.org/web/20210221083106/https://twitter.com/BehindUrBadDays/status/1363405771023781888): pic.twitter.com/oB6HVoWvL7
* [21 February 2021](https://web.archive.org/web/20210221082554/https://twitter.com/BehindUrBadDays/status/1363404473322926080): In 10 years, all the US, Saudi, and Israeli military 'might' can't defeat a bunch of barefoot Yemenis with AK-47s. Lol. Muslim my ass.
* [21 February 2021](https://web.archive.org/web/20210221082125/https://twitter.com/BehindUrBadDays/status/1363403337807331328): Is it still propaganda if jews say it?  https://twitter.com/TheSkotzman/status/1269641161829998593  pic.twitter.com/A9QpKvQV5t
* [21 February 2021](https://web.archive.org/web/20210221080521/https://twitter.com/BehindUrBadDays/status/1363399328795156480): Question:   Are you jewish? https://twitter.com/TheSkotzman/status/1363276932096421888
* [21 February 2021](https://web.archive.org/web/20210221075838/https://twitter.com/BehindUrBadDays/status/1363397667511009280): Hi, darlin! Didn't get a notification for this. That's like the 4th reply I didn't see. Stupid jews.   Hope you had a good day! 🤗
* [21 February 2021](https://web.archive.org/web/20210221075727/https://twitter.com/BehindUrBadDays/status/1363397368868188160): Lol
* [21 February 2021](https://web.archive.org/web/20210221061717/https://twitter.com/BehindUrBadDays/status/1363372117019009027): Show me a picture on your phone that has your energy. Not a selfie.  https://twitter.com/distolero/status/1363262923821481989  pic.twitter.com/UPq3rPzggH
* [21 February 2021](https://web.archive.org/web/20210221060653/https://twitter.com/BehindUrBadDays/status/1363369507302080512): Looks like an A20 to me. Nice. 😁
* [21 February 2021](https://web.archive.org/web/20210221060351/https://twitter.com/BehindUrBadDays/status/1363368728432361472): Aww. I didn't even know you posted this. My feet will go wherever yours go, baby. Thank you for taking me hiking. I love you. ❤😘
* [21 February 2021](https://web.archive.org/web/20210221060024/https://twitter.com/BehindUrBadDays/status/1363367881677959170): Hiya, honey! 🤗❤
* [21 February 2021](https://web.archive.org/web/20210221055901/https://twitter.com/BehindUrBadDays/status/1363367547517755393): Thanks, darlin. 🤗
* [21 February 2021](https://web.archive.org/web/20210221054419/https://twitter.com/BehindUrBadDays/status/1363363846388350977): Where's Nef?   Mark Mac?  Boingo?  We're missing some frens.
* [21 February 2021](https://web.archive.org/web/20210221053847/https://twitter.com/BehindUrBadDays/status/1363362482765656064): Yes, indeed.
* [21 February 2021](https://web.archive.org/web/20210221053706/https://twitter.com/BehindUrBadDays/status/1363362033081720834): I know I'm racist. https://twitter.com/Tuned___/status/1363347014499643396
* [21 February 2021](https://web.archive.org/web/20210221034155/https://twitter.com/BehindUrBadDays/status/1363329252540764162): Damn, it feels good to be White.  https://twitter.com/kitttygomeow/status/1363208786316562432  pic.twitter.com/zVgpvmXTI7
* [21 February 2021](https://web.archive.org/web/20210221030356/https://twitter.com/BehindUrBadDays/status/1363323475461603328): Likewise. It's going pretty good. We went hiking today. 😁
* [21 February 2021](https://web.archive.org/web/20210221015132/https://twitter.com/BehindUrBadDays/status/1363305240519450632): Hi, darlin. 😁🤗
* [21 February 2021](https://web.archive.org/web/20210221003858/https://twitter.com/BehindUrBadDays/status/1363287007783497730): Hi, sweetie! 🤗❤
* [21 February 2021](https://web.archive.org/web/20210221002651/https://twitter.com/BehindUrBadDays/status/1363283960902615043): Hi there, darlin. 🤗
* [21 February 2021](https://web.archive.org/web/20210221002637/https://twitter.com/BehindUrBadDays/status/1363283869676548096): Nature gives us a lovely break from this ugly, jewed-up world. It's good to get outside, no matter the weather. Glad you enjoyed it, darlin.
* [21 February 2021](https://web.archive.org/web/20210221002448/https://twitter.com/BehindUrBadDays/status/1363283495888572417): @FashVip Good idea. Lol. 😁
* [21 February 2021](https://web.archive.org/web/20210221002433/https://twitter.com/BehindUrBadDays/status/1363283358030118915): Hi, darlin. All is well. Thank you. Hope you're having a good weekend. 🤗
* [20 February 2021](https://web.archive.org/web/20210221000008/https://twitter.com/BehindUrBadDays/status/1363277225248841730): pic.twitter.com/O5HyErWN2d
* [20 February 2021](https://web.archive.org/web/20210221000008/https://twitter.com/BehindUrBadDays/status/1363277225248841730): Went for a nice hike today. 🤗 pic.twitter.com/0lhQg8cf0n
* [20 February 2021](https://web.archive.org/web/20210220214401/https://twitter.com/BehindUrBadDays/status/1363242937782566917): Hiya, darlin! 😁
* [20 February 2021](https://web.archive.org/web/20210220214229/https://twitter.com/BehindUrBadDays/status/1363242617694216197): Well, hello there VIP. 🤗 Have a great weekend!
* [20 February 2021](https://web.archive.org/web/20210220214146/https://twitter.com/BehindUrBadDays/status/1363242393064132611): Hi there, darlin! 😊
* [20 February 2021](https://web.archive.org/web/20210220214100/https://twitter.com/BehindUrBadDays/status/1363242204223922177): Hi, darlin. Thank you for the compliment. 😊 Hope you're enjoying your weekend. 🤗
* [20 February 2021](https://web.archive.org/web/20210220213833/https://twitter.com/BehindUrBadDays/status/1363241558527664129): Hi there, darlin! 🤗 Thank you. We're about to go for a walk. How's your weekend going? 😊
* [20 February 2021](https://web.archive.org/web/20210220212342/https://twitter.com/BehindUrBadDays/status/1363237821545349120): They limit how many people you can follow in a day. I should be able to follow everyone back a little later. :)
* [20 February 2021](https://web.archive.org/web/20210220212218/https://twitter.com/BehindUrBadDays/status/1363237498609164291): God, I love you! 😍 You're home early, so let's think of something fun to do. 😈❤
* [20 February 2021](https://web.archive.org/web/20210220212006/https://twitter.com/BehindUrBadDays/status/1363236958030467073): Hi, Patrick! Thank you. Hope you're having a good weekend. 🤗
* [20 February 2021](https://web.archive.org/web/20210220211649/https://twitter.com/BehindUrBadDays/status/1363236160361926662): Hiya, Pitler! 😁
* [20 February 2021](https://web.archive.org/web/20210220211632/https://twitter.com/BehindUrBadDays/status/1363236047547740163): Hi there, darlin! 🤗 It's fairly warm here. Hope you're having a good day.
* [20 February 2021](https://web.archive.org/web/20210220203901/https://twitter.com/BehindUrBadDays/status/1363226583172075524): Unblocked. Still can't follow anyone back yet.   Hiya, Rooster. 🤗
* [20 February 2021](https://web.archive.org/web/20210220203817/https://twitter.com/BehindUrBadDays/status/1363226403303526402): Mornin, darlin. Hope you have a great day. 🤗
* [20 February 2021](https://web.archive.org/web/20210220203732/https://twitter.com/BehindUrBadDays/status/1363226220167655427): Hiya, Steven. 😆 pic.twitter.com/3xamJKEidW
* [20 February 2021](https://web.archive.org/web/20210220203630/https://twitter.com/BehindUrBadDays/status/1363225991733198855): Hi, darlin. It's going great so far. 🤗 Likewise!
* [20 February 2021](https://web.archive.org/web/20210220203559/https://twitter.com/BehindUrBadDays/status/1363225859616870405): Thank you. 😁
* [20 February 2021](https://web.archive.org/web/20210220203544/https://twitter.com/BehindUrBadDays/status/1363225800745574402): Hi, darlin. Thank you. 🤗
* [20 February 2021](https://web.archive.org/web/20210220203457/https://twitter.com/BehindUrBadDays/status/1363225598810869760): Accident. Block chain
* [20 February 2021](https://web.archive.org/web/20210220203220/https://twitter.com/BehindUrBadDays/status/1363224950006550528): @RadioactiveRedn  You'll never know how much I love you, and that's ok. Just know that it's more than you love me. ❤ 😍  P.S. You can't win this one on twitter. pic.twitter.com/eNm2oZ6jSw
* [20 February 2021](https://web.archive.org/web/20210220201753/https://twitter.com/BehindUrBadDays/status/1363221290669195267): GOOD AFTERNOON, NIGGER-HATERZ!! 🤗❤ pic.twitter.com/mtDrJO2uwY
* [20 February 2021](https://web.archive.org/web/20210220124925/https://twitter.com/BehindUrBadDays/status/1363108305305010176): 😉
* [20 February 2021](https://web.archive.org/web/20210220124913/https://twitter.com/BehindUrBadDays/status/1363107992175001600): And welcome back, darlin. Good to see ya. 🤗💕
* [20 February 2021](https://web.archive.org/web/20210220124913/https://twitter.com/BehindUrBadDays/status/1363107992175001600): I can't stand that jew. Constantly advocating for "us" White people to do something, while his jewish ass sits safely in japan.
* [20 February 2021](https://web.archive.org/web/20210220124253/https://twitter.com/BehindUrBadDays/status/1363106539876331523): Hi, sweetheart. Thank you! Have a wonderful day. 🤗😘❤
* [20 February 2021](https://web.archive.org/web/20210220095552/https://twitter.com/BehindUrBadDays/status/1363064770455343106): I know who all the jews are. They don't like me very much.
* [20 February 2021](https://web.archive.org/web/20210220095203/https://twitter.com/BehindUrBadDays/status/1363063758818533376): Wait. . . aren't you a jew? Lol. https://twitter.com/ApocalypseSkull/status/1362943633054457864
* [20 February 2021](https://web.archive.org/web/20210220074415/https://twitter.com/BehindUrBadDays/status/1363031628633812997): 😘
* [20 February 2021](https://web.archive.org/web/20210220074244/https://twitter.com/BehindUrBadDays/status/1363031274630377473): Aww. ☺ You're so sweet. He really *is* wonderful. God has truly blessed me. We get along so well. ❤
* [20 February 2021](https://web.archive.org/web/20210220074012/https://twitter.com/BehindUrBadDays/status/1363030602115653632): Have to finish Cowboy Bebop first. 😁
* [20 February 2021](https://web.archive.org/web/20210220073745/https://twitter.com/BehindUrBadDays/status/1363029992549056512): 😆😘❤
* [20 February 2021](https://web.archive.org/web/20210220073553/https://twitter.com/BehindUrBadDays/status/1363029546447106050): OY VEY!
* [20 February 2021](https://web.archive.org/web/20210220073359/https://twitter.com/BehindUrBadDays/status/1363029089293115392): Hi, darlin! Thank you. 🤗
* [20 February 2021](https://web.archive.org/web/20210220073316/https://twitter.com/BehindUrBadDays/status/1363028877916991490): Yes. pic.twitter.com/xiFnQMnva1
* [20 February 2021](https://web.archive.org/web/20210220073134/https://twitter.com/BehindUrBadDays/status/1363028481634938880): He's got Ecksteins and Dickenhorsts in his family tree (grandparents).
* [20 February 2021](https://web.archive.org/web/20210220072836/https://twitter.com/BehindUrBadDays/status/1363027711791411203): He's a jew. The ultimate appropriator.
* [20 February 2021](https://web.archive.org/web/20210220072659/https://twitter.com/BehindUrBadDays/status/1363027259137937408): LOL. I'm kinda head-over-heels in love with him. 😆
* [20 February 2021](https://web.archive.org/web/20210220071240/https://twitter.com/BehindUrBadDays/status/1363023715898900480): @RadioactiveRedn  You are... pic.twitter.com/ijjXuhO02h
* [20 February 2021](https://web.archive.org/web/20210220071146/https://twitter.com/BehindUrBadDays/status/1363023474474835969): Aww. 😊😴🙏
* [20 February 2021](https://web.archive.org/web/20210220071014/https://twitter.com/BehindUrBadDays/status/1363023057091182593): Lol
* [20 February 2021](https://web.archive.org/web/20210220065358/https://twitter.com/BehindUrBadDays/status/1363019009772433408): It's a compilation of Der Sturmer, Richard Burton, and a few others. 😊
* [20 February 2021](https://web.archive.org/web/20210220061832/https://twitter.com/BehindUrBadDays/status/1363010066304139264): A thread I did a few years ago...   2,000 Years of jewish Ritual Murder  https://archive.org/details/2000YearsJewishRitualMurder
* [20 February 2021](https://web.archive.org/web/20210220061434/https://twitter.com/BehindUrBadDays/status/1363009074284101633): There are 2,000 years worth of historical accounts of jews kidnapping, torturing, crucifying, and draining the blood of Christian children. What do they do with that blood? They use it in their passover matzo.   This is open gloating/mockery. 👇 https://twitter.com/JComm_NewsFeeds/status/1225454493422112768
* [20 February 2021](https://web.archive.org/web/20210220054429/https://twitter.com/BehindUrBadDays/status/1363001419326971905): In the thousands of years your subhuman race has been on this earth, you've yet to conquer water. Slow down, sambo. https://twitter.com/Tv09337856/status/1362996244570865669
* [20 February 2021](https://web.archive.org/web/20210220051614/https://twitter.com/BehindUrBadDays/status/1362994389564469253): 5'5   😆
* [20 February 2021](https://web.archive.org/web/20210220051432/https://twitter.com/BehindUrBadDays/status/1362993923963162630): We're all retarded sometimes, darlin. Some of us more than others. 😆
* [20 February 2021](https://web.archive.org/web/20210220051254/https://twitter.com/BehindUrBadDays/status/1362993559792726016): LOL. No. I was talking about you. 😂
* [20 February 2021](https://web.archive.org/web/20210220051140/https://twitter.com/BehindUrBadDays/status/1362993259560206338): I meant to say  *must* talk like a shorty. Lol.   6'1 is pretty tall.
* [20 February 2021](https://web.archive.org/web/20210220050718/https://twitter.com/BehindUrBadDays/status/1362992176700022786): Lol. I just talk like a shorty. But I'm a tough little cookie. Grew up with a southern dad (say uncle) and brothers. 🤪
* [20 February 2021](https://web.archive.org/web/20210220050516/https://twitter.com/BehindUrBadDays/status/1362991481829683200): Very close. 🙃
* [20 February 2021](https://web.archive.org/web/20210220050350/https://twitter.com/BehindUrBadDays/status/1362991291504746497): Hello there, darlin. 😁
* [20 February 2021](https://web.archive.org/web/20210220050244/https://twitter.com/BehindUrBadDays/status/1362990942282743808): Lol. I'm a shorty, but perfect for RR. 😁
* [20 February 2021](https://web.archive.org/web/20210220045506/https://twitter.com/BehindUrBadDays/status/1362989080078921728): I am smol.
* [20 February 2021](https://web.archive.org/web/20210220044039/https://twitter.com/BehindUrBadDays/status/1362985449426403333): Better yet...   Research  Lavon Affair Dancing Israelis USS Liberty Ritual Murder
* [20 February 2021](https://web.archive.org/web/20210220040858/https://twitter.com/BehindUrBadDays/status/1362977461940588544): "Hello, fellow martians!"  https://twitter.com/blukngt/status/1362969830475718659  pic.twitter.com/ErXxkblLuG
* [20 February 2021](https://web.archive.org/web/20210220035817/https://twitter.com/BehindUrBadDays/status/1362974741192200192): Follow-back limit reached. Will follow everyone back as soon as possible. 😊🤪
* [20 February 2021](https://web.archive.org/web/20210220034709/https://twitter.com/BehindUrBadDays/status/1362971970388787200): Hiya, darlin. Thank you. 🤗
* [20 February 2021](https://web.archive.org/web/20210220034553/https://twitter.com/BehindUrBadDays/status/1362971640099930114): Holy shit. 🤣
* [20 February 2021](https://web.archive.org/web/20210220033912/https://twitter.com/BehindUrBadDays/status/1362969973682040833): Thank you, darlin. 🤗
* [20 February 2021](https://web.archive.org/web/20210220033842/https://twitter.com/BehindUrBadDays/status/1362969832501764100): Hi there, sweetie pie! 🤗😘
* [20 February 2021](https://web.archive.org/web/20210220033803/https://twitter.com/BehindUrBadDays/status/1362969727677722630): Synagogue of satan.
* [20 February 2021](https://web.archive.org/web/20210220033740/https://twitter.com/BehindUrBadDays/status/1362969612334284800): Hi, darlin. Thank you! 😁
* [20 February 2021](https://web.archive.org/web/20210220033731/https://twitter.com/BehindUrBadDays/status/1362969532005044225): Hiya, darlin! 🤗
* [20 February 2021](https://web.archive.org/web/20210220033538/https://twitter.com/BehindUrBadDays/status/1362969094719479808): Good Lord! 🤣
* [20 February 2021](https://web.archive.org/web/20210220031128/https://twitter.com/BehindUrBadDays/status/1362962946779930624): Thank you, darlin. 😁🤗
* [20 February 2021](https://web.archive.org/web/20210220025901/https://twitter.com/BehindUrBadDays/status/1362959854474850304): Hi, sweetie. Thank you. 😘
* [20 February 2021](https://web.archive.org/web/20210220024534/https://twitter.com/BehindUrBadDays/status/1362956484729065474): Hi darlin. Thank you! 🤗
* [20 February 2021](https://web.archive.org/web/20210220021245/https://twitter.com/BehindUrBadDays/status/1362948182146179073): Aww. You're so sweet. Lol. 😘
* [20 February 2021](https://web.archive.org/web/20210220021203/https://twitter.com/BehindUrBadDays/status/1362948055520210949): Lol. Hi, sweetie! 😘
* [20 February 2021](https://web.archive.org/web/20210220021143/https://twitter.com/BehindUrBadDays/status/1362947886342938632): LOL. They made me change my good Avi. 😏😆
* [20 February 2021](https://web.archive.org/web/20210220021101/https://twitter.com/BehindUrBadDays/status/1362947755245768704): Bonjour, mon cheri! 😁 I'm good. Hope you're having a great weekend. Thank you, darlin. 🤗
* [20 February 2021](https://web.archive.org/web/20210220020922/https://twitter.com/BehindUrBadDays/status/1362947359219539968): That I am. 😆 Hi, darlin. 🤗
* [20 February 2021](https://web.archive.org/web/20210220020307/https://twitter.com/BehindUrBadDays/status/1362945797457924097): Thank you. Love you. 😘❤
* [20 February 2021](https://web.archive.org/web/20210220015844/https://twitter.com/BehindUrBadDays/status/1362944688966279168): Hiya! 🤗
* [20 February 2021](https://web.archive.org/web/20210220015839/https://twitter.com/BehindUrBadDays/status/1362944612395008002): Thank you. 😁
* [20 February 2021](https://web.archive.org/web/20210220015803/https://twitter.com/BehindUrBadDays/status/1362944522209161217): Hi, darlin! Thank you. 🤗
* [20 February 2021](https://web.archive.org/web/20210220015733/https://twitter.com/BehindUrBadDays/status/1362944423601070081): Hi, sweetie! Thank you. 😘❤
* [20 February 2021](https://web.archive.org/web/20210220014654/https://twitter.com/BehindUrBadDays/status/1362941708804177920): jews have no sense of humor. 😏  Hi, my beautiful friend! 🤗😘❤
* [20 February 2021](https://web.archive.org/web/20210220014515/https://twitter.com/BehindUrBadDays/status/1362941183870324736): Ok, jew. 😂  https://twitter.com/KayaJones/status/1122161371855118341  pic.twitter.com/ThDWVgiUUS
* [20 February 2021](https://web.archive.org/web/20210220013803/https://twitter.com/BehindUrBadDays/status/1362939503699197957): 😆
* [20 February 2021](https://web.archive.org/web/20210220013743/https://twitter.com/BehindUrBadDays/status/1362939420542971916): Their kvetching is hysterical.  I agree. Our people are gonna have to fight back at some point. All in God's time.
* [20 February 2021](https://web.archive.org/web/20210220013607/https://twitter.com/BehindUrBadDays/status/1362939002706395141): Hello there, darlin! 🤗
* [20 February 2021](https://web.archive.org/web/20210220013338/https://twitter.com/BehindUrBadDays/status/1362938350458568707): jews get really butthurt when their lies stop working. They have a tendency to lash out. It's quite comical.
* [20 February 2021](https://web.archive.org/web/20210220013043/https://twitter.com/BehindUrBadDays/status/1362937626303602693): LOL. 😅
* [20 February 2021](https://web.archive.org/web/20210220012641/https://twitter.com/BehindUrBadDays/status/1362936650695868417): They keep me pretty shadowbanned. I'm a threat. It's a badge of honor. ⚔🛡
* [20 February 2021](https://web.archive.org/web/20210220012309/https://twitter.com/BehindUrBadDays/status/1362935752317886464): She's good. Happy and chubby. 😁
* [20 February 2021](https://web.archive.org/web/20210220011449/https://twitter.com/BehindUrBadDays/status/1362933635159056384): 😆 Good. As always. Thank you, Paulie. Hope you're enjoying your weekend.
* [20 February 2021](https://web.archive.org/web/20210220011306/https://twitter.com/BehindUrBadDays/status/1362933186909601794): Hiya, Paulie! 🤗💕
* [20 February 2021](https://web.archive.org/web/20210220011239/https://twitter.com/BehindUrBadDays/status/1362933109306580995): ❤
* [20 February 2021](https://web.archive.org/web/20210220010938/https://twitter.com/BehindUrBadDays/status/1362932304922951680): Hiya, darlin! Thank you. 😊🤗
* [20 February 2021](https://web.archive.org/web/20210220010302/https://twitter.com/BehindUrBadDays/status/1362930693551063044): Hiya! Thank you. 😁
* [20 February 2021](https://web.archive.org/web/20210220004410/https://twitter.com/BehindUrBadDays/status/1362925872001540099): Something like that. Geez. 😆
* [20 February 2021](https://web.archive.org/web/20210220004325/https://twitter.com/BehindUrBadDays/status/1362925712362139649): Hi, darlin! Long time no see. Thank you! 🤗
* [20 February 2021](https://web.archive.org/web/20210220004249/https://twitter.com/BehindUrBadDays/status/1362925590777634819): Hi, darlin! Thank you. 🤗
* [20 February 2021](https://web.archive.org/web/20210220004029/https://twitter.com/BehindUrBadDays/status/1362924927611994114): ☺
* [20 February 2021](https://web.archive.org/web/20210220003926/https://twitter.com/BehindUrBadDays/status/1362924722430869504): Howdy, darlin! Thank you. 😊🤗
* [20 February 2021](https://web.archive.org/web/20210220003836/https://twitter.com/BehindUrBadDays/status/1362924550279884801): Hiya, darlin! Thank you. 😁
* [20 February 2021](https://web.archive.org/web/20210220003415/https://twitter.com/BehindUrBadDays/status/1362923397005598720): Hmm.. I might have to try that. 🤔😁
* [20 February 2021](https://web.archive.org/web/20210220003302/https://twitter.com/BehindUrBadDays/status/1362923046412124160): Hi, darlin. Thank you. 🤗
* [20 February 2021](https://web.archive.org/web/20210220002936/https://twitter.com/BehindUrBadDays/status/1362922233577037824): 👍
* [20 February 2021](https://web.archive.org/web/20210220002813/https://twitter.com/BehindUrBadDays/status/1362921923785740289): It's over 130 now. I've lost count. Lol.
* [20 February 2021](https://web.archive.org/web/20210220002539/https://twitter.com/BehindUrBadDays/status/1362921252831309824): RR made that one for me. 😆
* [20 February 2021](https://web.archive.org/web/20210220002527/https://twitter.com/BehindUrBadDays/status/1362921145088040963): Hi there, darlin! 🤗😁
* [20 February 2021](https://web.archive.org/web/20210220002349/https://twitter.com/BehindUrBadDays/status/1362920789989859328): Thank you. 😘
* [20 February 2021](https://web.archive.org/web/20210220002232/https://twitter.com/BehindUrBadDays/status/1362920504001257474): Apparently, they'll suspend you if you repost the same Avi. I learned that the hard way. Lol
* [20 February 2021](https://web.archive.org/web/20210220002140/https://twitter.com/BehindUrBadDays/status/1362920245837635585): They have nothing to do with their time until I show up. They spend their days stalking me. Quite pathetic.
* [20 February 2021](https://web.archive.org/web/20210220002104/https://twitter.com/BehindUrBadDays/status/1362920048902500355): Lol. It seems to happen to me quite often. Hi, darlin! 🤗
* [20 February 2021](https://web.archive.org/web/20210220002015/https://twitter.com/BehindUrBadDays/status/1362919874180300805): Lol. 😆
* [20 February 2021](https://web.archive.org/web/20210220001948/https://twitter.com/BehindUrBadDays/status/1362919797449711617): SWEETIEST KAAAATE!! 🤗❤  Thank you!
* [20 February 2021](https://web.archive.org/web/20210220001803/https://twitter.com/BehindUrBadDays/status/1362919334163718144): Hi, darlin. Thanks! 🤗
* [20 February 2021](https://web.archive.org/web/20210220001718/https://twitter.com/BehindUrBadDays/status/1362919142450483200): Hi there, Imperator! 🤗😁
* [20 February 2021](https://web.archive.org/web/20210220001650/https://twitter.com/BehindUrBadDays/status/1362919024162713604): Not even back for 30 minutes. Geez.
* [20 February 2021](https://web.archive.org/web/20210220001425/https://twitter.com/BehindUrBadDays/status/1362918430236700673): Lol
* [20 February 2021](https://web.archive.org/web/20210220001300/https://twitter.com/BehindUrBadDays/status/1362918090779078661): Hi, darlin! Thank you. 🤗
* [20 February 2021](https://web.archive.org/web/20210220001209/https://twitter.com/BehindUrBadDays/status/1362917852697817091): Thank you, darlin! 🤗
* [20 February 2021](https://web.archive.org/web/20210220000944/https://twitter.com/BehindUrBadDays/status/1362917239817658369): Lol. F*cking babies. pic.twitter.com/1tMlHfPXEF
* [20 February 2021](https://web.archive.org/web/20210220000448/https://twitter.com/BehindUrBadDays/status/1362916033783336964): Hiya, handsome! 🤗💕
* [20 February 2021](https://web.archive.org/web/20210220000351/https://twitter.com/BehindUrBadDays/status/1362915812181479424): Hi, darlin! 🤗😁
* [20 February 2021](https://web.archive.org/web/20210220000337/https://twitter.com/BehindUrBadDays/status/1362915701510590472): Hi, darlin. Thank you. Good to see you, as always. 🤗
* [20 February 2021](https://web.archive.org/web/20210220000249/https://twitter.com/BehindUrBadDays/status/1362915489144569856): LOL. Hi, Ricky. Thank you, darlin. 🤗❤
* [20 February 2021](https://web.archive.org/web/20210220000157/https://twitter.com/BehindUrBadDays/status/1362915328322392069): I don't blame you. It's amazing how quickly they grow up when you're not there.
* [19 February 2021](https://web.archive.org/web/20210219235930/https://twitter.com/BehindUrBadDays/status/1362914649470099456): Note to new followers: This is a highly antisemitic/racist account. Don't follow if you can't handle it. 😁
* [19 February 2021](https://web.archive.org/web/20210219235653/https://twitter.com/BehindUrBadDays/status/1362914028587266050): That'll be fun! I miss mine. They're on the other side of the country.
* [19 February 2021](https://web.archive.org/web/20210219235537/https://twitter.com/BehindUrBadDays/status/1362913705655164929): Gonna reach my follow back limit soon. I promise I'll follow everybody back as soon as I'm able. ❤🤗
* [19 February 2021](https://web.archive.org/web/20210219235324/https://twitter.com/BehindUrBadDays/status/1362913141869465603): Hi. Thank you. 😁
* [19 February 2021](https://web.archive.org/web/20210219235310/https://twitter.com/BehindUrBadDays/status/1362913072772501506): Hi, honey! Thank you. Hope you're having a good weekend. 😘❤
* [19 February 2021](https://web.archive.org/web/20210219235224/https://twitter.com/BehindUrBadDays/status/1362912901665808393): Hi, darlin! Thank you.   Lol. 🤗
* [19 February 2021](https://web.archive.org/web/20210219234909/https://twitter.com/BehindUrBadDays/status/1362912100830638080): Well, thank you kind sir. 🤗
* [19 February 2021](https://web.archive.org/web/20210219234840/https://twitter.com/BehindUrBadDays/status/1362911949399408642): Hi, darlin! 🤗 You must be shadowbanned. I didn't see this in my notifications.
* [19 February 2021](https://web.archive.org/web/20210219234619/https://twitter.com/BehindUrBadDays/status/1362911374180032514): Hiya, Bilbo. Thank you, darlin. 🤗
* [19 February 2021](https://web.archive.org/web/20210219234546/https://twitter.com/BehindUrBadDays/status/1362911224770494466): For the 130+ time. Lol. I've lost count. Thank you, darlin. 🤗
* [19 February 2021](https://web.archive.org/web/20210219234520/https://twitter.com/BehindUrBadDays/status/1362911075780485121): Thank you, darlin. 😊
* [19 February 2021](https://web.archive.org/web/20210219234520/https://twitter.com/BehindUrBadDays/status/1362910998626205704): Hiya, Rooster. Thank you. 🤗😁
* [19 February 2021](https://web.archive.org/web/20210219234009/https://twitter.com/BehindUrBadDays/status/1362909814058332164): Hi, darlin! Thank you. 🤗
* [19 February 2021](https://web.archive.org/web/20210219233504/https://twitter.com/BehindUrBadDays/status/1362908516286103553): 😂 We can do that later. 😈😘
* [19 February 2021](https://web.archive.org/web/20210219233412/https://twitter.com/BehindUrBadDays/status/1362908325130756097): Mine was that the jews are 'Gods chosen people'  Gross. 🤢
* [19 February 2021](https://web.archive.org/web/20210219233308/https://twitter.com/BehindUrBadDays/status/1362907970980438017): Going pretty good. No complaints here. Thank you, Patrick. 😁
* [19 February 2021](https://web.archive.org/web/20210219233143/https://twitter.com/BehindUrBadDays/status/1362907658244808704): 😆
* [19 February 2021](https://web.archive.org/web/20210219232905/https://twitter.com/BehindUrBadDays/status/1362907018965774339): Hi! 🤗
* [19 February 2021](https://web.archive.org/web/20210219232828/https://twitter.com/BehindUrBadDays/status/1362906872941019139): Hiya, darlin! Good to see ya. Hope you have a great weekend! 🤗
* [19 February 2021](https://web.archive.org/web/20210219232233/https://twitter.com/BehindUrBadDays/status/1362905392125276165): Funny, we were talking about them yesterday.
* [19 February 2021](https://web.archive.org/web/20210219232205/https://twitter.com/BehindUrBadDays/status/1362905269269913602): Doesn't bother me a bit. I'm used to it. It's nice to know that I'm driving some jews mad. Lol
* [19 February 2021](https://web.archive.org/web/20210219232020/https://twitter.com/BehindUrBadDays/status/1362904819510444036): Hi, darlin. Thank you. 🤗
* [19 February 2021](https://web.archive.org/web/20210219231840/https://twitter.com/BehindUrBadDays/status/1362904390512828421): 😖 Gross. What was the ethnicity of the apartment-dwellers?
* [19 February 2021](https://web.archive.org/web/20210219231730/https://twitter.com/BehindUrBadDays/status/1362904136216416256): Of course. It's inevitable.
* [19 February 2021](https://web.archive.org/web/20210219231634/https://twitter.com/BehindUrBadDays/status/1362903843772780546): Hi, darlin! 🤗😁
* [19 February 2021](https://web.archive.org/web/20210219230627/https://twitter.com/BehindUrBadDays/status/1362901323671351303): Hi there. Thank you. 🤗
* [19 February 2021](https://web.archive.org/web/20210219230544/https://twitter.com/BehindUrBadDays/status/1362901150803107842): Hiya! Thank you. 🤗
* [19 February 2021](https://web.archive.org/web/20210219230520/https://twitter.com/BehindUrBadDays/status/1362901055382708227): Hi, darlin! Thank you. 🤗❤
* [19 February 2021](https://web.archive.org/web/20210219230502/https://twitter.com/BehindUrBadDays/status/1362900970653556737): Hi! 🤗
* [19 February 2021](https://web.archive.org/web/20210219230512/https://twitter.com/BehindUrBadDays/status/1362900908460412928): Hi there, darlin! Thank you. 🤗
* [19 February 2021](https://web.archive.org/web/20210219225801/https://twitter.com/BehindUrBadDays/status/1362899219581988876): 🤗😘😍❤ pic.twitter.com/sNL3BVbrNI
* [19 February 2021](https://web.archive.org/web/20210219225644/https://twitter.com/BehindUrBadDays/status/1362898867860230146): @RadioactiveRedn  Hi, sexy. 😘😍❤
* [19 February 2021](https://web.archive.org/web/20210219223326/https://twitter.com/BehindUrBadDays/status/1362892989174059008): HELL-OOO, BIGOTS! 🤗❤ pic.twitter.com/fKRUx5sVq0
* [19 February 2021](https://web.archive.org/web/20210219045709/https://twitter.com/BehindUrBadDays/status/1362627156728307725): Imagine my fucking shock. pic.twitter.com/BNq7F5MOj8
* [18 February 2021](https://web.archive.org/web/20210218215849/https://twitter.com/BehindUrBadDays/status/1362521948308336642): It's called 'jewish supremacy'  Get used to it.
