## Archived tweets for clampdownonjews
### Content warning: racism and antisemitism
More information: https://github.com/TwitterArchives/KYE#readme

The list below includes 58 archived tweets by
[clampdownonjews](https://twitter.com/clampdownonjews).




This report was generated by [@AcctHunter](https://twitter.com/accthunter) using ✨[cancel-culture](https://github.com/travisbrown/cancel-culture)✨,
an open source project by [Travis Brown](https://twitter.com/travisbrown). You can create your own
updated version of this document by checking out and configuring the repository and then running
the following commands:

```bash
$ cargo build --release
$ target/release/twcc deleted-tweets --report clampdownonjews
```

Please note that all tweets quoted here are sourced from the
[Wayback Machine](https://web.archive.org) and were not directly accessed through the Twitter API or
any Twitter client.



* [16 February 2021](https://web.archive.org/web/20210216033530/https://twitter.com/clampdownonjews/status/1361519445345062917): Pita = Greek  Bagels = Polish   jews are just appropriators.
* [16 February 2021](https://web.archive.org/web/20210216033055/https://twitter.com/clampdownonjews/status/1361518329727344641): I like bagels too, Mr Polish man.
* [16 February 2021](https://web.archive.org/web/20210216032932/https://twitter.com/clampdownonjews/status/1361517942475657216): Lmao.   Matt, I like hummus too. I get the same treatment from him. 😌 He doesn't know the origins of hummus.
* [16 February 2021](https://web.archive.org/web/20210216032542/https://twitter.com/clampdownonjews/status/1361517014943105026): Lol
* [16 February 2021](https://web.archive.org/web/20210216032419/https://twitter.com/clampdownonjews/status/1361516699929907206): pic.twitter.com/loS0F6zVwn
* [16 February 2021](https://web.archive.org/web/20210216032249/https://twitter.com/clampdownonjews/status/1361516263231512579): I would accept this position with honor. 😁
* [16 February 2021](https://web.archive.org/web/20210216032200/https://twitter.com/clampdownonjews/status/1361516087657918473): https://twitter.com/DChauv_Respktr/status/1361496463738609667  pic.twitter.com/F7TI9cXCZd
* [16 February 2021](https://web.archive.org/web/20210216030605/https://twitter.com/clampdownonjews/status/1361512109385814016): Mischlings are their greatest asset. The ultimate subversive parasite.
* [16 February 2021](https://web.archive.org/web/20210216013451/https://twitter.com/clampdownonjews/status/1361489131642052613): B..bu..but... race is just a social construct.   I hope White people aren't stupid enough to get this vaccine. https://twitter.com/Breaking911/status/1361474296086990849
* [16 February 2021](https://web.archive.org/web/20210216012812/https://twitter.com/clampdownonjews/status/1361487418763800577): Those were the days.
* [16 February 2021](https://web.archive.org/web/20210216011941/https://twitter.com/clampdownonjews/status/1361485319523028994): I need to be in charge of ethnostate admission.   I can sense a jew's presence before I ever lay eyes on the filthy demon.  Not a drop of jew-blood gets in.  NO QUARTER.  NO EXCEPTIONS.
* [16 February 2021](https://web.archive.org/web/20210216011128/https://twitter.com/clampdownonjews/status/1361483237168537603): You know you were aiming for the goblin behind that wall. 😌
* [16 February 2021](https://web.archive.org/web/20210216000412/https://twitter.com/clampdownonjews/status/1361466297284849665): You said the curse word... poodle. Lol.   Rewarding good behavior produces much better results than scolding bad behavior. Teach him using small treats. Before long, good behavior will become second nature. :)
* [15 February 2021](https://web.archive.org/web/20210215235635/https://twitter.com/clampdownonjews/status/1361464393943248900): Hi there, sweetie pie. 🤗
* [15 February 2021](https://web.archive.org/web/20210215235611/https://twitter.com/clampdownonjews/status/1361464280357380096): Hiya, darlin. It's going pretty good. Just doing some laundry and cleaning. 😁 It's raining, and I've got some nice jazz playing. 🎶🎺🎸
* [15 February 2021](https://web.archive.org/web/20210215235455/https://twitter.com/clampdownonjews/status/1361463976299663362): Hi, darlin. 🤗
* [15 February 2021](https://web.archive.org/web/20210215235409/https://twitter.com/clampdownonjews/status/1361463774658502658): Hebrew is a jewish language that didn't even exist until about 140-200 AD. The original OT was written in Chaldee/Aramaic. They refer to God as Moryo Aloho, and Christ as Eshoa.   I wasn't trying to argue. Just wanted to know if you had looked into it. :)
* [15 February 2021](https://web.archive.org/web/20210215235127/https://twitter.com/clampdownonjews/status/1361463122511335427): I've been a Christian since I was 5. My dad is a pastor and was a missionary for more than 15 years. I've read the Bible 8 times, from Genesis to Revelation.  The Latin Vulgate OT (as well as almost every other OT Bible translation) is based off the jewish Masoretic Text.
* [15 February 2021](https://web.archive.org/web/20210215224032/https://twitter.com/clampdownonjews/status/1361445229136539648): She's not mine. We did a job yesterday and she was there. She's a good girl. Likes peanut butter pretzels. 😁
* [15 February 2021](https://web.archive.org/web/20210215221952/https://twitter.com/clampdownonjews/status/1361440032947458054): 🤗❤
* [15 February 2021](https://web.archive.org/web/20210215221633/https://twitter.com/clampdownonjews/status/1361439242677678081): Hiya, sweetie! 🤗❤
* [15 February 2021](https://web.archive.org/web/20210215221617/https://twitter.com/clampdownonjews/status/1361439146154156033): Never better. Thanks, darlin. 🤗
* [15 February 2021](https://web.archive.org/web/20210215215119/https://twitter.com/clampdownonjews/status/1361432867130122244): Have you looked in to where the name 'yahweh' comes from?   The only name God ever gave in the Bible was "I Am", which is what Jesus called himself. "Before Abraham was, I Am." pic.twitter.com/jeIlfrXizG
* [15 February 2021](https://web.archive.org/web/20210215213619/https://twitter.com/clampdownonjews/status/1361429083788222464): Hi there, darlin. Como estas? 🤗
* [15 February 2021](https://web.archive.org/web/20210215212619/https://twitter.com/clampdownonjews/status/1361426582787694592): Hiya, General. 🤗
* [15 February 2021](https://web.archive.org/web/20210215210030/https://twitter.com/clampdownonjews/status/1361420092165091329): Hi there, darlin. 🤗
* [15 February 2021](https://web.archive.org/web/20210215205832/https://twitter.com/clampdownonjews/status/1361419586214653952): It's rainy here too. Very cozy. 😁
* [15 February 2021](https://web.archive.org/web/20210215205732/https://twitter.com/clampdownonjews/status/1361419340453539840): Hello there, lovely lady! I hope you're having a wonderful day. 🤗😘❤
* [15 February 2021](https://web.archive.org/web/20210215205559/https://twitter.com/clampdownonjews/status/1361418875749900291): 😘😍❤ pic.twitter.com/xSQwMuIWDg
* [15 February 2021](https://web.archive.org/web/20210215205226/https://twitter.com/clampdownonjews/status/1361418052382773250): We're doing fantastic. Thank you, darlin.   LOL. They wish they had my identity. They've been trying for 6 years. 😂
* [15 February 2021](https://web.archive.org/web/20210215202138/https://twitter.com/clampdownonjews/status/1361410270837444611): Hi there, darlin! 🤗
* [15 February 2021](https://web.archive.org/web/20210215202049/https://twitter.com/clampdownonjews/status/1361410118043136001): But... what if I run out of ossygen? 😫😜
* [15 February 2021](https://web.archive.org/web/20210215201930/https://twitter.com/clampdownonjews/status/1361409758507331584): Hiya, honey! 🤗 How's your Monday going?
* [15 February 2021](https://web.archive.org/web/20210215201834/https://twitter.com/clampdownonjews/status/1361409530605625344): 😁 pic.twitter.com/Xy8YagV3R2
* [15 February 2021](https://web.archive.org/web/20210215201659/https://twitter.com/clampdownonjews/status/1361409162425507842): Is *it* obsessed with me too? Good grief.   How's your day going, Patrick? 😁🤗
* [15 February 2021](https://web.archive.org/web/20210215201540/https://twitter.com/clampdownonjews/status/1361408823047585792): Hi there, Don. 🤗
* [15 February 2021](https://web.archive.org/web/20210215201523/https://twitter.com/clampdownonjews/status/1361408744693800965): Good afternoon, Imperator. 🤗 Hope you're having a great Monday.
* [15 February 2021](https://web.archive.org/web/20210215201451/https://twitter.com/clampdownonjews/status/1361408572484067336): @RadioactiveRedn  I'm gonna diiiie. I need CPR. Come kiss me, revive me, and bring me back to life. It's the only way I'll survive. 😄😚❤ pic.twitter.com/2j01aZYxqS
* [15 February 2021](https://web.archive.org/web/20210215200848/https://twitter.com/clampdownonjews/status/1361407033790984192): GOOD AFTERNOON, RACISTS! 🤗❤ pic.twitter.com/pMZLPrULBN
* [15 February 2021](https://web.archive.org/web/20210215100929/https://twitter.com/clampdownonjews/status/1361256212508016643): Everything went exactly how it was supposed to. There's nowhere else I'd rather be than with you. I love you... more than you'll ever know. 😘
* [15 February 2021](https://web.archive.org/web/20210215092715/https://twitter.com/clampdownonjews/status/1361245602663653379): That was fun. 🌧🌬
* [15 February 2021](https://web.archive.org/web/20210215092408/https://twitter.com/clampdownonjews/status/1361244817204776961): Ouch
* [15 February 2021](https://web.archive.org/web/20210215092211/https://twitter.com/clampdownonjews/status/1361244342199853057): She was snippy when we first got there. Wanted attention, but was skittish, so she tried to bite me 2x. Then I gave her a peanut butter pretzel and she spent the next 3 hours in my lap and/or playing with me. Lol. She heard RR coming in and was looking at the door in the pic. 😁
* [15 February 2021](https://web.archive.org/web/20210215074231/https://twitter.com/clampdownonjews/status/1361219249910341633): Love you the most! 😍
* [15 February 2021](https://web.archive.org/web/20210215034246/https://twitter.com/clampdownonjews/status/1361158930450108416): Hiya, Steven. 🤗
* [15 February 2021](https://web.archive.org/web/20210215022316/https://twitter.com/clampdownonjews/status/1361138889973403652): My new friend: Cocoa the Chihuahua. 🤗 pic.twitter.com/Ghga8etk2b
* [15 February 2021](https://web.archive.org/web/20210215021240/https://twitter.com/clampdownonjews/status/1361136286279475202): Lightening 🌩
* [15 February 2021](https://web.archive.org/web/20210215021039/https://twitter.com/clampdownonjews/status/1361135736599113730): Happy Valentine's Day, beautiful! Hope you have a lovely, blessed day. 🤗💕😘
* [15 February 2021](https://web.archive.org/web/20210215020618/https://twitter.com/clampdownonjews/status/1361134630498304003): The 144,000 were Israelites.   First century Christians.   The FIRSTfruits redeemed unto God from among men. (Revelation 14:4)
* [15 February 2021](https://web.archive.org/web/20210215012520/https://twitter.com/clampdownonjews/status/1361124346379468802): He's the patron Saint of courtly love, so it still fits. But... I hear you. It can still be fun though. It's tradition.
* [15 February 2021](https://web.archive.org/web/20210215012403/https://twitter.com/clampdownonjews/status/1361123984989777921): 😌  😁  Happy Valentine's Day, handsome Joe. 🤗💕
* [15 February 2021](https://web.archive.org/web/20210215012306/https://twitter.com/clampdownonjews/status/1361123788419600384): A bunch of jews died that day. Truly a reason to celebrate.
* [15 February 2021](https://web.archive.org/web/20210215012052/https://twitter.com/clampdownonjews/status/1361123159722782722): I'll certainly try. 😆
* [15 February 2021](https://web.archive.org/web/20210215012052/https://twitter.com/clampdownonjews/status/1361123159722782722): Thank you, darlin. Gonna grill some ribs later, maybe watch a scary movie (so I can snuggle closer to my sweetheart). 😁  Have a blessed day. 😊
* [15 February 2021](https://web.archive.org/web/20210215012520/https://twitter.com/clampdownonjews/status/1361124346379468802): It's a Christian holiday. That's why some people don't celebrate it.   Saint Valentine was a Christian martyr. pic.twitter.com/kShtKKInkR
* [15 February 2021](https://web.archive.org/web/20210215012052/https://twitter.com/clampdownonjews/status/1361123159722782722): 🤗
* [15 February 2021](https://web.archive.org/web/20210215074231/https://twitter.com/clampdownonjews/status/1361219249910341633): You are the love of my life. Happy Valentine's Day, baby!   I love you forever! 😍❤ pic.twitter.com/4uBQNbwlH2
* [15 February 2021](https://web.archive.org/web/20210215012052/https://twitter.com/clampdownonjews/status/1361123159722782722): HAPPY VALENTINE'S DAY, JEW-HATERS! ❤ YOU'RE MY FAVORITE GROUP OF PEOPLE! 🤗 pic.twitter.com/BvZ0BmBQtG
